MolSSI-Education/periodic-table

elements/manganese.md

Issues #18. This pull request adds a page for Manganese

Added page for manganese

---

elements/chromium.md

This pull request adds a page for Chromium.

Added chromium.md with content to elements.

---

elements/neon.md

Added neon page.

---

elements/nitrogen.md

This pull request adds a page for Nitrogen

Add page and information for Nitrogen

---

elements/copper.md

This pull request adds a page for Copper.

add page and information for Copper

---

elements/mercury.md

`print("Hello world!)`
Hello world!

added Mercury page

---

elements/yttrium.md

I noticed that yttrium did not have a page in the neat periodic table, so here is a page for yttrium!

Added page for yttrium

---

elements/niobium.md

Added informative description of Niobium

Added description for niobium

---

elements/nobelium.md

Nobelium deserves some recognition on your periodic table of the elements. I added one sentence of information and included the atomic number and symbol.

Add some info about nobelium

---

elements/silver.md

There was no page for Silver, so I created the page and populated the page with information about silver.

Add information about Silver

---

elements/iron.md

I saw that iron was missing in your periodic table! I added some info.

Added an element Iron

---

elements/cesium.md
elements/cesium.md~

Cesium was not included. This has been remedied.

Added Cesium

---

elements/chlorine.md

Adding some minor information about chlorine

Adding information about chlorine

---

elements/carbon.md

Add linebreaks to carbon

---

elements/boron.md

This PR will add line breaks to boron.  Resolves #46.

Add line breaks to boron

---

elements/titanium.md

With this PR we are finally bringing **Titanium** to the list of the elements. MolSSi's Periodic Table cannot be completed without this. 
This PR resolves #47

Add element titanium

---

elements/florine.md

added florine

---

elements/argon.md

Added page for Argon.

---

elements/gold.md

First fact for gold.md

---

elements/neon.md

Changes to neon

---

elements/helium.md

Expanded the fun facts about Helium

Added Helium fact

---

elements/helium.md

Add Facts section and first fact.

add fact to helium

---

elements/iron.md

Explanation about the appearance of the _iron_ element in the periodic table.

Changes to iron

---

elements/neon.md

added more description to neon

add info about Ne

---

elements/mercury.md

Please do not consider this request, as the fact added to mercury is silly

Added a silly comment to mercury.md

---

elements/carbon.md

modified carbon

---

elements/lithium.md

Numbered existing facts of lithium and added a fact for lithium.

added new fact for lithium

---

elements/copper.md

Added pun for copper. Who doesn't like bad scientific puns?

Added fact for copper

---

elements/seaborgium.md

Expand upon Seaborgium details.

Changes to seaborgium

---

elements/neon.md

Changed neon.md

---

elements/oxygen.md

Updated oxygen

---

elements/lead.md

corrected typo 'ancient'

---

elements/titanium.md

Added fact for Titanium

---

elements/barium.md

Added pun for barium

---

elements/yttrium.md

Changes upon yttrium

---

elements/potassium.md

Just added atomic number and element symbol to potassium.md file

add Potassium page

---

elements/sulfur.md

changed sulfur.md

---

elements/platinum.md

This PR will add a new page for Platinum with facts about the element. Resolves #45

Added information on platinum

---

elements/holmium.md

Added new information for periodic table on Holmium

Added new element holmium

---

elements/nobelium.md

add numbering and additional fact

add fact for nobelium

---

elements/oxygen.md

Added atomic weight and more info about oxygen.

edit oxygen

---

elements/cerium.md

Information about the cerium element initiated here, it was not present in the original file.

add cerium

---

elements/silver.md

Fun fact about silver and Argentina.

silver update

---

elements/silicon.md

Added information about Silicon

Added information about silicon

---

elements/darmstadtium.md

Added the element of Darmstadtium with basic information.

Darmstadtium

---

elements/florine.md
elements/fluorine.md

Fluorine file was incorrectly named to "Florine.md", so the file name is changed to "Fluorine.md".
Also, some additional information is added to that element.

Correct Fluorine file name and add some information

---

elements/gallium.md

Added information about Gallium.

added gallium

---

elements/rhodium.md

This request adds a page for Rhodium
Resolved issue #150

Add element page for Rhodium

---

elements/sodium.md

We added information about Sodium physical properties.

Improved description of the Sodium element

---

elements/krypton.md

Started page for Krypton

---

elements/oxygen.md

We added history information of oxygen.

updated history information to oxygen

---

elements/.radium.md

Create the radium page and add description of Ra

---

elements/polonium.md

This pull request add a page for Po
Addresses #146

added polonium 

---

elements/sodium.md

add more information to sodium

---

_data/elements.json
_layouts/home.html
script/main.js

this commit gets rid of making a request for each element. it should speed up loading of the page

update main page to build using liquid

---

elements/calcium.md

I just added the atomic symbol, number, and burn color of Calcium.

add Ca symbol, atomic number, burn color

---

elements/phosphorus.md

Added page for Phosphorus. 
Closes issue 228.

Added a page for Phosphorus

---

elements/neptunium.md

Created a file for Np, supplemented with information about the element.

---

elements/aluminium.md

Adding new aluminum page and information

adding info about aluminium

---

elements/argon.md

adding info about argon

---

elements/gold.md

Added where the symbol Au comes from and added a joke

Added information and a joke to gold.md

---

elements/iodine.md

add page for iodine

---

elements/radon.md

added radon page with atomic number

added radon page

---

elements/ytterbium.md

Copied the first few sentences from the Wikipedia page of Yb.

update Ytterbium page

---

elements/template.md

adding an initial template based on Gold and Bismuth

---

elements/francium.md

francium page made

---

elements/cadmium.md

create and update cadmium page

---

elements/gold.md

add one line of fun fact of gold

add info about gold

---

elements/arsenic.md

Describing how arsenic inhibit enzymes.

Biological impact of Arsenic poisoning.

---

elements/antimony.md

In this pull request, I added to the element "antimony.md" file. It is a funny joke to remember what the element is.

Added an intuitive joke to the file

---

elements/livermorium.md

In this Pull Request, I added the page 'livermorium.md' and added small information about element.

add livermorium page

---

elements/copper.md

In this Pull request I added a fact about copper in the "copper.md" file

added fact to copper

---

elements/cobalt.md

In this pull request, I updated the page `cobalt.md`:
- Information added about cobalt in the core of vitamin B12

cobalt element updated
